
paths:
  tmp: tmp

cache:
  type: phpfastcache
  config:
    path: '{path:tmp}'

games:
  aq:
    label: Action Quake
    class: Games\Quake2
    host: aq.games
    port: 27910
    password: salaisuus
    vars:
      teamplay:
        description: Enable teamplay
        options: [ 0, 1 ]
        restart: true
      dmflags:
        description: Somewhat crypted server flags
  cs:
    label: Counter-Strike 1.6
    class: Games\CS
    host: cs.games
    port: 27015
    password: salaisuus
    vars:
      mp_friendlyfire:
        label: Friendly fire
        description: Enable or disable friendly fire
        options: [ 0, 1 ]
        restart: true
      mp_forcechasecam:
        label: Spectator mode
        description: Spectator mode, 0 = anyone, 1 = team and no free look, 2 = first person only, 3 = team and free look
        options: [ 0, 1, 2, 3 ]
      mp_freezetime:
        label: Freeze at round start
        description: Freeze seconds at round start
        options: [ 0, 3, 6, 10 ]
      mp_roundtime:
        label: Minutes per round
        description: Minutes for a single round to last
        options: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 ]
      mp_timelimit:
        label: Minutes per map
        description: Minutes for a single map to last (0 to disable)
        options: [ 0, 10, 15, 20, 30 ]
      mp_winlimit:
        label: Wins per map
        description: After how many wins the map is changed (0 to disable)
        options: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
      mp_autoteambalance:
        description: Balance teams automatically
        options: [ 0, 1 ]
      mp_limitteams:
        description: Maximum player count difference between teams (0 to disable)
        options: [ 0, 1, 2, 3, 4, 5 ]
      mp_autokick:
        description: Kick idle players
        options: [ 0, 1 ]
      mp_startmoney:
        description: Start with this much money
        options: [ 400, 800, 1600, 3200, 6400, 12800 ]
      sv_restart:
        description: Restart server after setting this timeout (seconds)
        options: [ 10, 5, 1 ]
    metadata:
      actions:
        Add Bot Normal T:
          cmd: pb add 50 1 1
        Add Bot Normal CT:
          cmd: pb add 50 1 2
        Kill Bots:
          cmd: pb killbots
        Remove Bots:
          cmd: pb removebots
        # Add Bot Normal T:
        #   cmd: yb add 4 0 1
        # Add Bot Normal CT:
        #   cmd: yb add 4 0 2
        # Kill Bots:
        #   cmd: yb killall
        # Remove Bots:
        #   cmd: yb kickall
  cod2:
    label: 'Call of Duty 2'
    class: Games\Cod2
    host: cod2.games
    port: 28961
    password: salaisuus
  cod4:
    label: 'Call of Duty 4: Modern Warface'
    class: Games\Cod4
    host: cod4.games
    port: 28960
    password: salaisuus
