
setup:
  debug: true

log:
  syslog:
    enabled: false
    level: INFO
  console:
    enabled: true
    level: VERBOSE
  file:
    level: VERBOSE

cache:
  enabled: true
  call: Symfony\Component\Cache\Simple\FilesystemCache@
  args:
    - games          # namespace
    - 300            # default ttl
    - '{path.cache}' # path

doctrine:
  sql:
    driver: mysqli
    host: sql.lan
    dbname: games
    user: dev
    password: dev

games:
  aq:
    label: Action Quake
    class: Games\Quake2
    host: aq.games
    port: 27910
    password: salaisuus
    vars:
      teamplay:
        description: Enable teamplay
        options: [ 0, 1 ]
        restart: true
      dmflags:
        description: Somewhat crypted server flags
  cs:
    label: Counter-Strike 1.6
    class: Games\CS
    host: cs.games
    port: 27015
    password: salaisuus
    vars:
      mp_friendlyfire:
        description: Enable or disable friendly fire
        options: [ 0, 1 ]
        restart: true
      mp_forcechasecam:
        description: Spectator mode, 0 = anyone, 1 = team and no free look, 2 = first person only, 3 = team and free look
        options: [ 0, 1, 2, 3 ]
      mp_freezetime:
        description: Freeze seconds at round start
        options: [ 0, 3, 6, 10 ]
      mp_roundtime:
        description: Minutes for a single round to last
        options: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 20, 30, 60 ]
      mp_timelimit:
        description: Minutes for a single map to last (0 to disable)
        options: [ 0, 10, 15, 20, 30 ]
      mp_winlimit:
        description: After how many wins the map is changed (0 to disable)
        options: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 13, 15, 17, 20, 30 ]
      mp_autoteambalance:
        description: Balance teams automatically
        options: [ 0, 1 ]
      mp_limitteams:
        description: Maximum player count difference between teams (0 to disable)
        options: [ 0, 1, 2, 3, 4, 5 ]
      mp_autokick:
        description: Kick idle players
        options: [ 0, 1 ]
      mp_startmoney:
        description: Start with this much money
        options: [ 400, 800, 1600, 3200, 6400, 12800 ]
      mp_flashlight:
        description: Allow use of flashlight
        options: [ 0, 1 ]
      pb_chat:
        description: Whether or not bots talk when dead
        options: [ 0, 1 ]
      pb_bot_join_team:
        description: Force bots to join team
        options: [ 'ANY', 'T', 'CT' ]
      pb_minbotskill:
        description: New bot will be at least this good
        options: [ 20, 30, 40, 50, 60, 70, 80, 90 ]
      pb_maxbotskill:
        description: New bot will be at most this good
        options: [ 30, 40, 50, 60, 70, 80, 90, 100 ]
      pb_bot_quota_match:
        description: 'How maxbots/minbots affect: 0 = bots + humans, >1 * humans = bot count'
        options: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
      pb_minbots:
        description: Minimum amount of bots
        options: [ 0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30 ]
      pb_maxbots:
        description: Maximum amount of bots
        options: [ 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30 ]
    metadata:
      actions:
        Restart:
          cmd: sv_restart 1
        Add Bot T:
          cmd: pb add 101 5 1 5
        Add Bot CT:
          cmd: pb add 101 5 2 5
        Kill Bots:
          cmd: pb killbots
        Remove Bots:
          cmd: pb removebots
  cod2:
    label: 'Call of Duty 2'
    class: Games\Cod2
    host: cod2.games
    port: 28961
    password: salaisuus
  cod4:
    label: 'Call of Duty 4: Modern Warface'
    class: Games\Cod4
    host: cod4.games
    port: 28960
    password: salaisuus
