setup:
  debug: true
  formats:
    - html
    - json

# twig setup
twig:
  debug: false
  cache: false

# define module configurations and sometimes classes to be autoloaded
modules:
  Placeholder: Games/Placeholder

# basic site js/css includes
javascript:
  - https://code.jquery.com/jquery-3.3.1.min.js
  - https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/bootstrap3-dialog/1.34.7/js/bootstrap-dialog.min.js
  - jquery.rest.min.js
  - vue.js
  - common:*
  - games:*
  - site.js
css:
  - https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/bootstrap3-dialog/1.34.7/css/bootstrap-dialog.min.css
  - https://use.fontawesome.com/releases/v5.5.0/css/all.css
  - common:*
  - games:*
  - site.css
