
games:
  aq2:
    label: Action Quake
    class: Games\Quake2
    host: lanit.lan
    port: 27910
    password: salaisuus
  cs:
    label: Counter-Strike 1.6
    class: Games\CS
    host: lanit.lan
    port: 27015
    password: salaisuus
  cod2:
    label: 'Call of Duty 2'
    class: Games\Cod2
    host: lanit.lan
    port: 28961
    password: salaisuus
  cod4:
    label: 'Call of Duty 4: Modern Warface'
    class: Games\Cod4
    host: lanit.lan
    port: 28960
    password: salaisuus
