
aq2:
  label: Action Quake
  class: App\Game\Quake2
  host: dev.lan
  port: 27910
  password: jussi

cs:
  label: Counter-Strike 1.6
  class: App\Game\CS
  host: desktop.lan
  port: 27015
  password: salaisuus

cod2:
  label: Call of Duty 2
  class: App\Game\Cod2
  host: dev.lan
  port: 28961
  password: salaisuus

cod4:
  label: 'Call of Duty 4: Modern Warface'
  class: App\Game\Cod4
  host: dev.lan
  port: 28960
  password: salaisuus

