
index:
  pattern: /
  call: Games\GamesController@index

game:
  pattern: /{=call:Games\Game@getGame,object}
  call: Games\GamesController@game

api:games:
  pattern: /api/games/{=call:Games\Game@getGame,object|=call:Games\Game@getGames,array}
  call: Games\ApiController@games
  format: json

api:games:cmd:
  pattern: /api/games/{=call:Games\Game@getGame,object}/cmd
  call: Games\ApiController@cmd
  format: json
  method: [ put, post ]

api:games:maps:
  pattern: /api/games/{game=call:Games\Game@getGame,object}/maps
  call: game@getMaps
  format: json

api:games:map:
  pattern: /api/games/{game=call:Games\Game@getGame,object}/map/{map}
  call: game@setMap(map)
  format: json

api:games:vars:
  pattern: /api/games/{=call:Games\Game@getGame,object}/vars/{|}
  call: Games\ApiController@vars
  format: json

api:games:players:
  pattern: /api/games/{=call:Games\Game@getGame,object}/players
  call: Games\ApiController@players
  format: json
